# production:
#   sync_all_reservations:
#     class: SyncAllReservationsJob
#     schedule: "every 5 minute"  
#   sync_properties:
#     class: SyncPropertiesJob
#     schedule: "every 5 minute"

development:
  sync_all_reservations:
    class: SyncAllReservationsJob
    schedule: "every 1 minute"  
  sync_properties:
    class: SyncPropertiesJob
    schedule: "every 1 minute"
